version: 2.1
jobs:
  build-backend:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - run: echo build-backend step
      - run: mkdir build_output
      - run: echo "Compiled" > build_output/compiled_output.txt
      - persist_to_workspace:
          root: build_output
          paths:
            - '*'

  build-frontend:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - run: echo build-frontend step

  test-backend:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - run: echo test-backend step
      - attach_workspace:
          at: ~/repo/workspace
      - run: cat ~/repo/workspace/compiled_output.txt

  test-frontend:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - run: echo test-frontend step

  integration-tests:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - run: echo integration-tests step

  deploy:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - run: echo deploy step
      - attach_workspace:
          at: ~/repo/workspace
      - run: cat ~/repo/workspace/compiled_output.txt

workflows:
  build-and-test:
    jobs:
      - build-backend
      - build-frontend
      - test-backend:
          requires:
            - build-backend
      - test-frontend:
          requires:
            - build-frontend
      - integration-tests:
          requires:
            - build-backend
            - build-frontend
      - deploy:
          requires:
            - test-backend
            - test-frontend
            - integration-tests
          filters:
            branches:
              only:
                - master
# build triger
