version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:latest

    working_directory: ~/repo

    steps:
      - run: echo build step

  test:
    docker:
      - image: circleci/node:latest

    working_directory: ~/repo

    steps:
      - run: echo test step

workflows:
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
