version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:latest

    working_directory: ~/repo

    steps:
      - run:
          name: build step
          command: echo build step

  test:
    docker:
      - image: circleci/node:latest

    working_directory: ~/repo

    steps:
      - run:
          name: test step
          command: echo test step

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
        requires:
          - build
